name: CI

on: [push]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy env example for initial composer setup
        run: cp .env.example .env

      - name: Install Dependencies
        uses: php-actions/composer@v6
        env:
          APP_ENV: analysis
        with:
          php_version: 8.0
          php_extensions: gd
          args: |
            --ignore-platform-req=ext-zip
            --ignore-platform-req=ext-imagick
            --ignore-platform-req=ext-bcmath
            --ignore-platform-req=ext-gd
            --ignore-platform-req=ext-pcntl
            --ignore-platform-req=ext-rdkafka
            --ignore-platform-req=ext-sockets
            --ignore-platform-req=ext-elastic_apm

      - name: PHP version
        run: php --version

      - name: Composer version
        run: composer --version

      - name: Test ext GD
        run: php -r "var_dump(extension_loaded('gd'));"

      - name: Test ext PDO
        run: php -r "var_dump(extension_loaded('pdo_pgsql'));"

      - name: Static Code Analysis
        run: composer analysis:run
