name: CI

on: [push]

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy env example for initial composer setup
        run: cp .env.example .env

      - uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          command: |
            --ignore-platform-req=ext-zip
            --ignore-platform-req=ext-imagick
            --ignore-platform-req=ext-bcmath
            --ignore-platform-req=ext-gd
            --ignore-platform-req=ext-pcntl
            --ignore-platform-req=ext-rdkafka
            --ignore-platform-req=ext-sockets
            --ignore-platform-req=ext-elastic_apm

      - name: Dependencies Audit
        run: composer audit

      - name: Static Code Analysis
        run: composer analysis:run
