name: PR Test

on:
  push:
    branches:
      - master

jobs:
  pr_test:
    name: Create PR Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create commits
        run: |
          git config user.name 'Alex Test'
          git config user.email 'aliaksandr.gg+testpr1@gmail.com'
          date +%s > test.txt
          git commit -m "Test Commit 1"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
